language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

notifications:
  email: true

sudo: false

script:
 - ./gradlew assembleDebug
